#!/bin/bash

echo "════════════════════════════════════════════════════════════════"
echo "📋 NEED YOUR AURORA ENDPOINT"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "You must manually check Aurora cluster status:"
echo ""
echo "OPTION 1: AWS CONSOLE"
echo "   1. Go to: https://console.aws.amazon.com/rds/"
echo "   2. Click 'Databases' on left"
echo "   3. Find 'beauzead-aurora-free'"
echo "   4. Copy the Endpoint URL (under 'Connectivity & security')"
echo ""
echo "OPTION 2: AWS CLI (if you have permission)"
echo "   aws rds describe-db-clusters \\\"
echo "     --db-cluster-identifier beauzead-aurora-free \\\"
echo "     --region us-east-1 \\\"
echo "     --query 'DBClusters[0].Endpoint' \\\"
echo "     --output text"
echo ""
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "After you have the ENDPOINT, run:"
echo ""
echo "  export ENDPOINT='your-endpoint-here'"
echo "  source beauzead-db-config.env"
echo ""
echo "Or update beauzead-db-config.env manually:"
echo ""
echo "  sed -i \"s/ENDPOINT_HERE/your-endpoint-here/g\" beauzead-db-config.env"
echo ""
echo "Then test connection:"
echo ""
echo "  psql -h your-endpoint -U beauzeadadmin -d beauzeaddb"
echo ""
